name: animated_multichild
description: Create ListView, GridView, Row or Column whose children are animated easily.
version: 0.0.2
homepage: https://github.com/sushmoyr/animated_multichild/
repository: https://github.com/sushmoyr/animated_multichild/

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
